name: home-monitoring

services:

  db:
    image: postgres:15.10
    env_file: db.env
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
      - home-monitoring-net
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  activemq:
    image: apache/activemq-classic:5.18.6
    env_file: activemq.env
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
    networks:
      - home-monitoring-net
    volumes:
      - ./activemq-conf/activemq.xml:/opt/apache-activemq/conf/activemq.xml
      - ./activemq-conf/camel.xml:/opt/apache-activemq/conf/camel.xml
      - ./activemq-conf/jetty-realm.properties:/opt/apache-activemq/conf/jetty-realm.properties
      - ./activemq-lib/postgresql-42.2.14.jar:/opt/apache-activemq/lib/postgresql-42.2.14.jar
      - ./activemq-lib/camel/camel-sql-2.25.4.jar:/opt/apache-activemq/lib/camel/camel-sql-2.25.4.jar
      - activemq-data:/opt/apache-activemq/data
    depends_on:
      - db

  node-red:
    image: nodered/node-red:2.1.3
    ports:
      - "1880:1880"
    networks:
      - home-monitoring-net
    volumes:
      - node-red-data:/data
    depends_on:
      - db
      - activemq

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    networks:
      - home-monitoring-net
#   volumes:
#     - ./grafana-conf:/etc/grafana/provisioning
    depends_on:
      - db

volumes:
  db-data:
  activemq-data:
  node-red-data:

networks:
  home-monitoring-net:
