name: home-monitoring

services:

  activemq:
    image: apache/activemq-classic:5.18.6
    env_file: activemq.env
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"
    volumes:
      - ./activemq-conf/activemq.xml:/opt/apache-activemq/conf/activemq.xml
      - ./activemq-conf/camel.xml:/opt/apache-activemq/conf/camel.xml
      - ./activemq-conf/jetty-realm.properties:/opt/apache-activemq/conf/jetty-realm.properties
      - ./activemq-lib/postgresql-42.2.14.jar:/opt/apache-activemq/lib/postgresql-42.2.14.jar
      - activemq-data:/opt/apache-activemq/data

volumes:
  activemq-data: